### PR TITLE
Generator API

### PR DESCRIPTION
**Pull request by ivanPrunier**
Some fixes will probably be pushed later but feel free to check it already.

Currently injecting the first user through `UserRepository()->find(1)` because Auth is not merged on my branch, I will do a quick hotfix after the merge to fix that.

### CODE REVIEW

**Comment by jeremNoel** [comment]
It can be cool if you update your PR with develop plz. :)

**Comment by ivanPrunier** [comment]
Honestly don't want to do that, last time it broke my docker and I'd rather not take the risk to be blocked while handling your comments
It doesn't change much though, almost nothing was repeated and I'll handle the conflicts when merging

**Comment by Backins** [comment]
I like your `unverified` tag :)

**Comment by ivanPrunier** [comment]
🖕😘

**Review by Backins — APPROVED** [review]

**Review by mehdou92 — APPROVED** [review]
Good stuff

**Review by benKazmierczak — APPROVED** [review]

**Pull request merged**
