### PR TITLE
Add user:create command

### PR DESCRIPTION
**Pull request by ivanPrunier**

### CODE REVIEW

**Review by Backins — CHANGES_REQUESTED** [review]
There is some problem : 
* User need login, password and email. In your code, we have 3 options (email, password and role)

And for an easily command : 
* Could you use interactive console ? Because : 
> php bin/console user:create email email@email.com password DSLSDdfslsdf434 ...

it's too long ! :'(

* Could you create password with faker or other ? And at the end of creating user, display generated password in the console ?

**Comment by ivanPrunier** [comment]
Fixed the login problem, but it's still not a interactive console. Will do it later.

**Review by Backins — APPROVED** [review]

**Review by Backins — APPROVED** [review]
Command is ok. I approve merging these changes

**Review by Backins — APPROVED** [review]
To close this PR, please add your review or submit your feedback : @mehdou92 @benKazmierczak @jeremNoel

**Review by mehdou92 — APPROVED** [review]

**Pull request merged**
