### PR TITLE
Adding a entity collapsible container

### PR DESCRIPTION
**Pull request by benKazmierczak**
I opened this PR for code tracking and codacy analysis
This PR groups the commits for the feature add entity
Thx for your feedback.

### CODE REVIEW

**Review by ivanPrunier — APPROVED** [review]

**Review by jeremNoel — APPROVED** [review]

**Comment by Backins** [comment]
@ivanPrunier @jeremNoel Remove your approvement. This PR has been open just for code tracking and codacy analysis (for the moment).

@benKazmierczak will notify us to approve his PR.

**Comment by Backins** [comment]
@benKazmierczak I saw your branch and your second column appear doesn't work.

I can't write anything in input. This is normal ?

**Comment by benKazmierczak** [comment]
> @benKazmierczak I saw your branch and your second column appear doesn't work.
> 
> I can't write anything in input. This is normal ?

@Backins No, it's not normal. I do not have this problem on my branch but check if you still have this problem after the evolutions I just brought

**Comment by benKazmierczak** [comment]
I made a big change for all the forms of the app. I passed the css forms in class.scss to avoid code repetition and I also secure our css rules for all types of form fields

**Comment by benKazmierczak** [comment]
Ready to merge

**Review by mehdou92 — APPROVED** [review]

**Review by Backins — APPROVED** [review]

**Pull request merged**
