### PR TITLE
Feature/homepage

### PR DESCRIPTION
**Pull request by Backins**
This pull request contains : 
* full front of the homepage
* include header 
  - This header is use in the homepage, but we can use the twig in the hub page too !
* include footer
* Responsive (with materialize only)
* I remove some link in twig (multiple call of same file)

### CODE REVIEW

**Comment by Backins** [comment]
@ivanPrunier can you check Codacy ? I think they is only one commit checked by Codacy :s

**Review by jeremNoel — COMMENTED** [review]
You had conflicts with materialize css to put !important?

**Comment by Backins** [comment]
Yes, to override materialize

**Review by jeremNoel — APPROVED** [review]

**Review by ivanPrunier — APPROVED** [review]
As I said, approved for me I trust you guys for the front part.

@Backins Codacy seems fine, what do you think is the problem?

**Review by benKazmierczak — APPROVED** [review]
ok for me

**Pull request merged**
