### PR TITLE
Feature/crud user

### PR DESCRIPTION
**Pull request by benKazmierczak**
PR contains:
- The generation of crud user
- Adding of faker
- Adding DataFixture
- The DataFixture User
- The profile page version mock figma (css includes)
- FormType User
- Adding the materialize icon library

Attention for the moment there is only the profile page (show) that is made.
The pages edit, new, index exist but they have not been retouched yet.

Thank you for your feedback.

### CODE REVIEW

**Comment by ivanPrunier** [comment]
If you have time to do it now, I think it would be great to create a `UserService` class to handle all the operations on the user entity. Then you could use it in the controller, and it would also be usable in other parts of the website (which we will eventually need) without duplicating code.

The `UserService` class should have a `UserRepository` attribute and all the needed methods (`getUser`, `getUsers`, `createUser` etc.). You then add a `userService` attribute to the `UserController` and just use the methods created before in the controller.

This can be done later if time is short for now, but it will need to be done for the MVP and the code review.

**Review by ivanPrunier — APPROVED** [review]
Approving but I won't merge it now, if @benKazmierczak has time to implement the `UserService` it would be good to do it now so we don't have to refacto more code in the future.

**Comment by mehdou92** [comment]
Agree with @ivanPrunier . Let's try the `UserService` @benKazmierczak  :)

**Review by mehdou92 — APPROVED** [review]

**Comment by Backins** [comment]
Many comments : 
* File :  signup.scss => line 18 => $color-livingCoralg ? Would not be `$livingCoral` ?
* If I compare from Figma, I have not the same style in signup page. This is normal ?
* 992px breakpoint, the bloc "Sign up to Mak'API" isn't align center


To fix "M is not defined, insert in the head of `pagelayout.twig.html` : 
> <script type="text/javascript" src="{{ asset('build/vendor.js') }}"></script>

**Pull request merged**
